SET REFERENTIAL_INTEGRITY FALSE;
delete from execucao_prova;
delete from prova_questao;
delete from prova;
delete from candidato;
delete from questao_assunto;
-- delete from questao_alternativa_anexos;
delete from questao_anexos;
delete from questao_alternativa;
delete from questao_gabarito;
delete from questao;
delete from nivel_dificuldade;
delete from area_conhecimento_assunto;
delete from assunto_assunto;
delete from assunto;
delete from area_conhecimento;
delete from empresa_telefone;
delete from empresa;